# Generated by Django 4.1.3 on 2022-12-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='plan',
            field=models.IntegerField(default=0),
        ),
    ]
